# Site settings
title: Rutvi Khamar
email: rkhamar2023@my.fit.edu
description: > # this means to ignore newlines until "baseurl:"
   Master's student in Data Science at NYU. Interested in Machine Learning, Natural Language Processing, and Statistics. Bachelor's from BITS Pilani.
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://www.rutvi02.github.io" # the base hostname & protocol for your site
production_url: "https://www.rutvi02.github.io"
github_username: rutvi02
permalink: /blog/:year/:month/:title.html

twitter:
  username: sargun_nagpal

sass:
  style: compressed

collections:
  publications:
    output: false

jekyll-mentions:
  base_url: https://twitter.com

plugins:
  - jekyll-sitemap
  - jekyll-feed
  - jekyll-seo-tag
  - jekyll-mentions
